/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.commoncategory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.nss.commoncategory.model.City;
import com.nss.commoncategory.model.CityModel;
import com.nss.commoncategory.model.CitySoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the City service. Represents a row in the &quot;nss_platform_city&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CityImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CityModelImpl extends BaseModelImpl<City> implements CityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a city model instance should use the <code>City</code> interface instead.
	 */
	public static final String TABLE_NAME = "nss_platform_city";

	public static final Object[][] TABLE_COLUMNS = {
		{"cityId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"code_", Types.VARCHAR}, {"countryId", Types.BIGINT},
		{"description", Types.VARCHAR}, {"priority", Types.INTEGER},
		{"active_", Types.BOOLEAN}, {"countCode", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("cityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("countryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("countCode", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nss_platform_city (cityId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(255) null,code_ VARCHAR(75) null,countryId LONG,description STRING null,priority INTEGER,active_ BOOLEAN,countCode INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table nss_platform_city";

	public static final String ORDER_BY_JPQL = " ORDER BY city.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nss_platform_city.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long CODE_COLUMN_BITMASK = 2L;

	public static final long COUNTRYID_COLUMN_BITMASK = 4L;

	public static final long NAME_COLUMN_BITMASK = 8L;

	public static final long PRIORITY_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static City toModel(CitySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		City model = new CityImpl();

		model.setCityId(soapModel.getCityId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setCode(soapModel.getCode());
		model.setCountryId(soapModel.getCountryId());
		model.setDescription(soapModel.getDescription());
		model.setPriority(soapModel.getPriority());
		model.setActive(soapModel.isActive());
		model.setCountCode(soapModel.getCountCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<City> toModels(CitySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<City> models = new ArrayList<City>(soapModels.length);

		for (CitySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return City.class;
	}

	@Override
	public String getModelClassName() {
		return City.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<City, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<City, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<City, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((City)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<City, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<City, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((City)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<City, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<City, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, City>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			City.class.getClassLoader(), City.class, ModelWrapper.class);

		try {
			Constructor<City> constructor =
				(Constructor<City>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<City, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<City, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<City, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<City, Object>>();
		Map<String, BiConsumer<City, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<City, ?>>();

		attributeGetterFunctions.put("cityId", City::getCityId);
		attributeSetterBiConsumers.put(
			"cityId", (BiConsumer<City, Long>)City::setCityId);
		attributeGetterFunctions.put("companyId", City::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<City, Long>)City::setCompanyId);
		attributeGetterFunctions.put("groupId", City::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<City, Long>)City::setGroupId);
		attributeGetterFunctions.put("userId", City::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<City, Long>)City::setUserId);
		attributeGetterFunctions.put("userName", City::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<City, String>)City::setUserName);
		attributeGetterFunctions.put("createDate", City::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<City, Date>)City::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", City::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<City, Date>)City::setModifiedDate);
		attributeGetterFunctions.put("name", City::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<City, String>)City::setName);
		attributeGetterFunctions.put("code", City::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<City, String>)City::setCode);
		attributeGetterFunctions.put("countryId", City::getCountryId);
		attributeSetterBiConsumers.put(
			"countryId", (BiConsumer<City, Long>)City::setCountryId);
		attributeGetterFunctions.put("description", City::getDescription);
		attributeSetterBiConsumers.put(
			"description", (BiConsumer<City, String>)City::setDescription);
		attributeGetterFunctions.put("priority", City::getPriority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<City, Integer>)City::setPriority);
		attributeGetterFunctions.put("active", City::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<City, Boolean>)City::setActive);
		attributeGetterFunctions.put("countCode", City::getCountCode);
		attributeSetterBiConsumers.put(
			"countCode", (BiConsumer<City, Integer>)City::setCountCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCityId() {
		return _cityId;
	}

	@Override
	public void setCityId(long cityId) {
		_cityId = cityId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON(include = false)
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON(include = false)
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public long getCountryId() {
		return _countryId;
	}

	@Override
	public void setCountryId(long countryId) {
		_columnBitmask |= COUNTRYID_COLUMN_BITMASK;

		if (!_setOriginalCountryId) {
			_setOriginalCountryId = true;

			_originalCountryId = _countryId;
		}

		_countryId = countryId;
	}

	public long getOriginalCountryId() {
		return _originalCountryId;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_columnBitmask = -1L;

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public int getCountCode() {
		return _countCode;
	}

	@Override
	public void setCountCode(int countCode) {
		_countCode = countCode;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), City.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public City toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, City>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CityImpl cityImpl = new CityImpl();

		cityImpl.setCityId(getCityId());
		cityImpl.setCompanyId(getCompanyId());
		cityImpl.setGroupId(getGroupId());
		cityImpl.setUserId(getUserId());
		cityImpl.setUserName(getUserName());
		cityImpl.setCreateDate(getCreateDate());
		cityImpl.setModifiedDate(getModifiedDate());
		cityImpl.setName(getName());
		cityImpl.setCode(getCode());
		cityImpl.setCountryId(getCountryId());
		cityImpl.setDescription(getDescription());
		cityImpl.setPriority(getPriority());
		cityImpl.setActive(isActive());
		cityImpl.setCountCode(getCountCode());

		cityImpl.resetOriginalValues();

		return cityImpl;
	}

	@Override
	public int compareTo(City city) {
		int value = 0;

		if (getPriority() < city.getPriority()) {
			value = -1;
		}
		else if (getPriority() > city.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof City)) {
			return false;
		}

		City city = (City)obj;

		long primaryKey = city.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		CityModelImpl cityModelImpl = this;

		cityModelImpl._setModifiedDate = false;

		cityModelImpl._originalName = cityModelImpl._name;

		cityModelImpl._originalCode = cityModelImpl._code;

		cityModelImpl._originalCountryId = cityModelImpl._countryId;

		cityModelImpl._setOriginalCountryId = false;

		cityModelImpl._originalActive = cityModelImpl._active;

		cityModelImpl._setOriginalActive = false;

		cityModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<City> toCacheModel() {
		CityCacheModel cityCacheModel = new CityCacheModel();

		cityCacheModel.cityId = getCityId();

		cityCacheModel.companyId = getCompanyId();

		cityCacheModel.groupId = getGroupId();

		cityCacheModel.userId = getUserId();

		cityCacheModel.userName = getUserName();

		String userName = cityCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cityCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cityCacheModel.createDate = createDate.getTime();
		}
		else {
			cityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cityCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cityCacheModel.name = getName();

		String name = cityCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			cityCacheModel.name = null;
		}

		cityCacheModel.code = getCode();

		String code = cityCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			cityCacheModel.code = null;
		}

		cityCacheModel.countryId = getCountryId();

		cityCacheModel.description = getDescription();

		String description = cityCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			cityCacheModel.description = null;
		}

		cityCacheModel.priority = getPriority();

		cityCacheModel.active = isActive();

		cityCacheModel.countCode = getCountCode();

		return cityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<City, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<City, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<City, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((City)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<City, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<City, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<City, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((City)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, City>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _cityId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _code;
	private String _originalCode;
	private long _countryId;
	private long _originalCountryId;
	private boolean _setOriginalCountryId;
	private String _description;
	private int _priority;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private int _countCode;
	private long _columnBitmask;
	private City _escapedModel;

}