/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.commoncategory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.nss.commoncategory.model.Continent;
import com.nss.commoncategory.model.ContinentModel;
import com.nss.commoncategory.model.ContinentSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Continent service. Represents a row in the &quot;nss_platform_continent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ContinentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContinentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContinentImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ContinentModelImpl
	extends BaseModelImpl<Continent> implements ContinentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a continent model instance should use the <code>Continent</code> interface instead.
	 */
	public static final String TABLE_NAME = "nss_platform_continent";

	public static final Object[][] TABLE_COLUMNS = {
		{"continentId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"internationalName", Types.VARCHAR}, {"code_", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"priority", Types.INTEGER},
		{"active_", Types.BOOLEAN}, {"countCode", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("continentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("internationalName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("countCode", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nss_platform_continent (continentId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(255) null,internationalName VARCHAR(255) null,code_ VARCHAR(75) null,description STRING null,priority INTEGER,active_ BOOLEAN,countCode INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table nss_platform_continent";

	public static final String ORDER_BY_JPQL =
		" ORDER BY continent.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nss_platform_continent.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long CODE_COLUMN_BITMASK = 2L;

	public static final long NAME_COLUMN_BITMASK = 4L;

	public static final long PRIORITY_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Continent toModel(ContinentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Continent model = new ContinentImpl();

		model.setContinentId(soapModel.getContinentId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setInternationalName(soapModel.getInternationalName());
		model.setCode(soapModel.getCode());
		model.setDescription(soapModel.getDescription());
		model.setPriority(soapModel.getPriority());
		model.setActive(soapModel.isActive());
		model.setCountCode(soapModel.getCountCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Continent> toModels(ContinentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Continent> models = new ArrayList<Continent>(soapModels.length);

		for (ContinentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ContinentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _continentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContinentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _continentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Continent.class;
	}

	@Override
	public String getModelClassName() {
		return Continent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Continent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Continent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Continent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Continent)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Continent, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Continent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Continent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Continent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Continent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Continent>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Continent.class.getClassLoader(), Continent.class,
			ModelWrapper.class);

		try {
			Constructor<Continent> constructor =
				(Constructor<Continent>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Continent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Continent, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Continent, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Continent, Object>>();
		Map<String, BiConsumer<Continent, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Continent, ?>>();

		attributeGetterFunctions.put("continentId", Continent::getContinentId);
		attributeSetterBiConsumers.put(
			"continentId",
			(BiConsumer<Continent, Long>)Continent::setContinentId);
		attributeGetterFunctions.put("companyId", Continent::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Continent, Long>)Continent::setCompanyId);
		attributeGetterFunctions.put("groupId", Continent::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Continent, Long>)Continent::setGroupId);
		attributeGetterFunctions.put("userId", Continent::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Continent, Long>)Continent::setUserId);
		attributeGetterFunctions.put("userName", Continent::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Continent, String>)Continent::setUserName);
		attributeGetterFunctions.put("createDate", Continent::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Continent, Date>)Continent::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Continent::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Continent, Date>)Continent::setModifiedDate);
		attributeGetterFunctions.put("name", Continent::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Continent, String>)Continent::setName);
		attributeGetterFunctions.put(
			"internationalName", Continent::getInternationalName);
		attributeSetterBiConsumers.put(
			"internationalName",
			(BiConsumer<Continent, String>)Continent::setInternationalName);
		attributeGetterFunctions.put("code", Continent::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<Continent, String>)Continent::setCode);
		attributeGetterFunctions.put("description", Continent::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<Continent, String>)Continent::setDescription);
		attributeGetterFunctions.put("priority", Continent::getPriority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<Continent, Integer>)Continent::setPriority);
		attributeGetterFunctions.put("active", Continent::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<Continent, Boolean>)Continent::setActive);
		attributeGetterFunctions.put("countCode", Continent::getCountCode);
		attributeSetterBiConsumers.put(
			"countCode",
			(BiConsumer<Continent, Integer>)Continent::setCountCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getContinentId() {
		return _continentId;
	}

	@Override
	public void setContinentId(long continentId) {
		_continentId = continentId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getInternationalName() {
		if (_internationalName == null) {
			return "";
		}
		else {
			return _internationalName;
		}
	}

	@Override
	public void setInternationalName(String internationalName) {
		_internationalName = internationalName;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_columnBitmask = -1L;

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public int getCountCode() {
		return _countCode;
	}

	@Override
	public void setCountCode(int countCode) {
		_countCode = countCode;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Continent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Continent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Continent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContinentImpl continentImpl = new ContinentImpl();

		continentImpl.setContinentId(getContinentId());
		continentImpl.setCompanyId(getCompanyId());
		continentImpl.setGroupId(getGroupId());
		continentImpl.setUserId(getUserId());
		continentImpl.setUserName(getUserName());
		continentImpl.setCreateDate(getCreateDate());
		continentImpl.setModifiedDate(getModifiedDate());
		continentImpl.setName(getName());
		continentImpl.setInternationalName(getInternationalName());
		continentImpl.setCode(getCode());
		continentImpl.setDescription(getDescription());
		continentImpl.setPriority(getPriority());
		continentImpl.setActive(isActive());
		continentImpl.setCountCode(getCountCode());

		continentImpl.resetOriginalValues();

		return continentImpl;
	}

	@Override
	public int compareTo(Continent continent) {
		int value = 0;

		if (getPriority() < continent.getPriority()) {
			value = -1;
		}
		else if (getPriority() > continent.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Continent)) {
			return false;
		}

		Continent continent = (Continent)obj;

		long primaryKey = continent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ContinentModelImpl continentModelImpl = this;

		continentModelImpl._setModifiedDate = false;

		continentModelImpl._originalName = continentModelImpl._name;

		continentModelImpl._originalCode = continentModelImpl._code;

		continentModelImpl._originalActive = continentModelImpl._active;

		continentModelImpl._setOriginalActive = false;

		continentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Continent> toCacheModel() {
		ContinentCacheModel continentCacheModel = new ContinentCacheModel();

		continentCacheModel.continentId = getContinentId();

		continentCacheModel.companyId = getCompanyId();

		continentCacheModel.groupId = getGroupId();

		continentCacheModel.userId = getUserId();

		continentCacheModel.userName = getUserName();

		String userName = continentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			continentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			continentCacheModel.createDate = createDate.getTime();
		}
		else {
			continentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			continentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			continentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		continentCacheModel.name = getName();

		String name = continentCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			continentCacheModel.name = null;
		}

		continentCacheModel.internationalName = getInternationalName();

		String internationalName = continentCacheModel.internationalName;

		if ((internationalName != null) && (internationalName.length() == 0)) {
			continentCacheModel.internationalName = null;
		}

		continentCacheModel.code = getCode();

		String code = continentCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			continentCacheModel.code = null;
		}

		continentCacheModel.description = getDescription();

		String description = continentCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			continentCacheModel.description = null;
		}

		continentCacheModel.priority = getPriority();

		continentCacheModel.active = isActive();

		continentCacheModel.countCode = getCountCode();

		return continentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Continent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Continent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Continent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Continent)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Continent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Continent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Continent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Continent)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Continent>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _continentId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _internationalName;
	private String _code;
	private String _originalCode;
	private String _description;
	private int _priority;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private int _countCode;
	private long _columnBitmask;
	private Continent _escapedModel;

}