/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.commoncategory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.nss.commoncategory.model.Country;
import com.nss.commoncategory.model.CountryModel;
import com.nss.commoncategory.model.CountrySoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Country service. Represents a row in the &quot;nss_commoncategory_country&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CountryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CountryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CountryImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CountryModelImpl
	extends BaseModelImpl<Country> implements CountryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a country model instance should use the <code>Country</code> interface instead.
	 */
	public static final String TABLE_NAME = "nss_commoncategory_country";

	public static final Object[][] TABLE_COLUMNS = {
		{"countryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"continentId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"internationalName", Types.VARCHAR},
		{"nationality", Types.VARCHAR}, {"code_", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"priority", Types.INTEGER},
		{"active_", Types.BOOLEAN}, {"countCode", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("countryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("continentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("internationalName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nationality", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("countCode", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nss_commoncategory_country (countryId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,continentId LONG,name VARCHAR(255) null,internationalName VARCHAR(255) null,nationality VARCHAR(255) null,code_ VARCHAR(75) null,description STRING null,priority INTEGER,active_ BOOLEAN,countCode INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table nss_commoncategory_country";

	public static final String ORDER_BY_JPQL = " ORDER BY country.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nss_commoncategory_country.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long CODE_COLUMN_BITMASK = 2L;

	public static final long NAME_COLUMN_BITMASK = 4L;

	public static final long PRIORITY_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Country toModel(CountrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Country model = new CountryImpl();

		model.setCountryId(soapModel.getCountryId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setContinentId(soapModel.getContinentId());
		model.setName(soapModel.getName());
		model.setInternationalName(soapModel.getInternationalName());
		model.setNationality(soapModel.getNationality());
		model.setCode(soapModel.getCode());
		model.setDescription(soapModel.getDescription());
		model.setPriority(soapModel.getPriority());
		model.setActive(soapModel.isActive());
		model.setCountCode(soapModel.getCountCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Country> toModels(CountrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Country> models = new ArrayList<Country>(soapModels.length);

		for (CountrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CountryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _countryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCountryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _countryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Country.class;
	}

	@Override
	public String getModelClassName() {
		return Country.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Country, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Country, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Country, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Country)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Country, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Country, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Country)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Country, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Country, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Country>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Country.class.getClassLoader(), Country.class, ModelWrapper.class);

		try {
			Constructor<Country> constructor =
				(Constructor<Country>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Country, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Country, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Country, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Country, Object>>();
		Map<String, BiConsumer<Country, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Country, ?>>();

		attributeGetterFunctions.put("countryId", Country::getCountryId);
		attributeSetterBiConsumers.put(
			"countryId", (BiConsumer<Country, Long>)Country::setCountryId);
		attributeGetterFunctions.put("companyId", Country::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Country, Long>)Country::setCompanyId);
		attributeGetterFunctions.put("groupId", Country::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Country, Long>)Country::setGroupId);
		attributeGetterFunctions.put("userId", Country::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Country, Long>)Country::setUserId);
		attributeGetterFunctions.put("userName", Country::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Country, String>)Country::setUserName);
		attributeGetterFunctions.put("createDate", Country::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Country, Date>)Country::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Country::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Country, Date>)Country::setModifiedDate);
		attributeGetterFunctions.put("continentId", Country::getContinentId);
		attributeSetterBiConsumers.put(
			"continentId", (BiConsumer<Country, Long>)Country::setContinentId);
		attributeGetterFunctions.put("name", Country::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Country, String>)Country::setName);
		attributeGetterFunctions.put(
			"internationalName", Country::getInternationalName);
		attributeSetterBiConsumers.put(
			"internationalName",
			(BiConsumer<Country, String>)Country::setInternationalName);
		attributeGetterFunctions.put("nationality", Country::getNationality);
		attributeSetterBiConsumers.put(
			"nationality",
			(BiConsumer<Country, String>)Country::setNationality);
		attributeGetterFunctions.put("code", Country::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<Country, String>)Country::setCode);
		attributeGetterFunctions.put("description", Country::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<Country, String>)Country::setDescription);
		attributeGetterFunctions.put("priority", Country::getPriority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<Country, Integer>)Country::setPriority);
		attributeGetterFunctions.put("active", Country::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<Country, Boolean>)Country::setActive);
		attributeGetterFunctions.put("countCode", Country::getCountCode);
		attributeSetterBiConsumers.put(
			"countCode", (BiConsumer<Country, Integer>)Country::setCountCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCountryId() {
		return _countryId;
	}

	@Override
	public void setCountryId(long countryId) {
		_countryId = countryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON(include = false)
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON(include = false)
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getContinentId() {
		return _continentId;
	}

	@Override
	public void setContinentId(long continentId) {
		_continentId = continentId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getInternationalName() {
		if (_internationalName == null) {
			return "";
		}
		else {
			return _internationalName;
		}
	}

	@Override
	public void setInternationalName(String internationalName) {
		_internationalName = internationalName;
	}

	@JSON
	@Override
	public String getNationality() {
		if (_nationality == null) {
			return "";
		}
		else {
			return _nationality;
		}
	}

	@Override
	public void setNationality(String nationality) {
		_nationality = nationality;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_columnBitmask = -1L;

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public int getCountCode() {
		return _countCode;
	}

	@Override
	public void setCountCode(int countCode) {
		_countCode = countCode;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Country.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Country toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Country>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CountryImpl countryImpl = new CountryImpl();

		countryImpl.setCountryId(getCountryId());
		countryImpl.setCompanyId(getCompanyId());
		countryImpl.setGroupId(getGroupId());
		countryImpl.setUserId(getUserId());
		countryImpl.setUserName(getUserName());
		countryImpl.setCreateDate(getCreateDate());
		countryImpl.setModifiedDate(getModifiedDate());
		countryImpl.setContinentId(getContinentId());
		countryImpl.setName(getName());
		countryImpl.setInternationalName(getInternationalName());
		countryImpl.setNationality(getNationality());
		countryImpl.setCode(getCode());
		countryImpl.setDescription(getDescription());
		countryImpl.setPriority(getPriority());
		countryImpl.setActive(isActive());
		countryImpl.setCountCode(getCountCode());

		countryImpl.resetOriginalValues();

		return countryImpl;
	}

	@Override
	public int compareTo(Country country) {
		int value = 0;

		if (getPriority() < country.getPriority()) {
			value = -1;
		}
		else if (getPriority() > country.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Country)) {
			return false;
		}

		Country country = (Country)obj;

		long primaryKey = country.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		CountryModelImpl countryModelImpl = this;

		countryModelImpl._setModifiedDate = false;

		countryModelImpl._originalName = countryModelImpl._name;

		countryModelImpl._originalCode = countryModelImpl._code;

		countryModelImpl._originalActive = countryModelImpl._active;

		countryModelImpl._setOriginalActive = false;

		countryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Country> toCacheModel() {
		CountryCacheModel countryCacheModel = new CountryCacheModel();

		countryCacheModel.countryId = getCountryId();

		countryCacheModel.companyId = getCompanyId();

		countryCacheModel.groupId = getGroupId();

		countryCacheModel.userId = getUserId();

		countryCacheModel.userName = getUserName();

		String userName = countryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			countryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			countryCacheModel.createDate = createDate.getTime();
		}
		else {
			countryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			countryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			countryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		countryCacheModel.continentId = getContinentId();

		countryCacheModel.name = getName();

		String name = countryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			countryCacheModel.name = null;
		}

		countryCacheModel.internationalName = getInternationalName();

		String internationalName = countryCacheModel.internationalName;

		if ((internationalName != null) && (internationalName.length() == 0)) {
			countryCacheModel.internationalName = null;
		}

		countryCacheModel.nationality = getNationality();

		String nationality = countryCacheModel.nationality;

		if ((nationality != null) && (nationality.length() == 0)) {
			countryCacheModel.nationality = null;
		}

		countryCacheModel.code = getCode();

		String code = countryCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			countryCacheModel.code = null;
		}

		countryCacheModel.description = getDescription();

		String description = countryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			countryCacheModel.description = null;
		}

		countryCacheModel.priority = getPriority();

		countryCacheModel.active = isActive();

		countryCacheModel.countCode = getCountCode();

		return countryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Country, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Country, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Country, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Country)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Country, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Country, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Country, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Country)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Country>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _countryId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _continentId;
	private String _name;
	private String _originalName;
	private String _internationalName;
	private String _nationality;
	private String _code;
	private String _originalCode;
	private String _description;
	private int _priority;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private int _countCode;
	private long _columnBitmask;
	private Country _escapedModel;

}