/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.commoncategory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.nss.commoncategory.model.District;
import com.nss.commoncategory.model.DistrictModel;
import com.nss.commoncategory.model.DistrictSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the District service. Represents a row in the &quot;nss_platform_district&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>DistrictModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DistrictImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DistrictImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DistrictModelImpl
	extends BaseModelImpl<District> implements DistrictModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a district model instance should use the <code>District</code> interface instead.
	 */
	public static final String TABLE_NAME = "nss_platform_district";

	public static final Object[][] TABLE_COLUMNS = {
		{"districtId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"code_", Types.VARCHAR}, {"countryId", Types.BIGINT},
		{"cityId", Types.BIGINT}, {"description", Types.VARCHAR},
		{"priority", Types.INTEGER}, {"active_", Types.BOOLEAN},
		{"countCode", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("districtId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("countryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("countCode", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nss_platform_district (districtId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(255) null,code_ VARCHAR(75) null,countryId LONG,cityId LONG,description STRING null,priority INTEGER,active_ BOOLEAN,countCode INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table nss_platform_district";

	public static final String ORDER_BY_JPQL =
		" ORDER BY district.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nss_platform_district.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long CITYID_COLUMN_BITMASK = 2L;

	public static final long CODE_COLUMN_BITMASK = 4L;

	public static final long NAME_COLUMN_BITMASK = 8L;

	public static final long PRIORITY_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static District toModel(DistrictSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		District model = new DistrictImpl();

		model.setDistrictId(soapModel.getDistrictId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setCode(soapModel.getCode());
		model.setCountryId(soapModel.getCountryId());
		model.setCityId(soapModel.getCityId());
		model.setDescription(soapModel.getDescription());
		model.setPriority(soapModel.getPriority());
		model.setActive(soapModel.isActive());
		model.setCountCode(soapModel.getCountCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<District> toModels(DistrictSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<District> models = new ArrayList<District>(soapModels.length);

		for (DistrictSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public DistrictModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _districtId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDistrictId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _districtId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return District.class;
	}

	@Override
	public String getModelClassName() {
		return District.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<District, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<District, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<District, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((District)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<District, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<District, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(District)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<District, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<District, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, District>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			District.class.getClassLoader(), District.class,
			ModelWrapper.class);

		try {
			Constructor<District> constructor =
				(Constructor<District>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<District, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<District, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<District, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<District, Object>>();
		Map<String, BiConsumer<District, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<District, ?>>();

		attributeGetterFunctions.put("districtId", District::getDistrictId);
		attributeSetterBiConsumers.put(
			"districtId", (BiConsumer<District, Long>)District::setDistrictId);
		attributeGetterFunctions.put("companyId", District::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<District, Long>)District::setCompanyId);
		attributeGetterFunctions.put("groupId", District::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<District, Long>)District::setGroupId);
		attributeGetterFunctions.put("userId", District::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<District, Long>)District::setUserId);
		attributeGetterFunctions.put("userName", District::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<District, String>)District::setUserName);
		attributeGetterFunctions.put("createDate", District::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<District, Date>)District::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", District::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<District, Date>)District::setModifiedDate);
		attributeGetterFunctions.put("name", District::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<District, String>)District::setName);
		attributeGetterFunctions.put("code", District::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<District, String>)District::setCode);
		attributeGetterFunctions.put("countryId", District::getCountryId);
		attributeSetterBiConsumers.put(
			"countryId", (BiConsumer<District, Long>)District::setCountryId);
		attributeGetterFunctions.put("cityId", District::getCityId);
		attributeSetterBiConsumers.put(
			"cityId", (BiConsumer<District, Long>)District::setCityId);
		attributeGetterFunctions.put("description", District::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<District, String>)District::setDescription);
		attributeGetterFunctions.put("priority", District::getPriority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<District, Integer>)District::setPriority);
		attributeGetterFunctions.put("active", District::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<District, Boolean>)District::setActive);
		attributeGetterFunctions.put("countCode", District::getCountCode);
		attributeSetterBiConsumers.put(
			"countCode", (BiConsumer<District, Integer>)District::setCountCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getDistrictId() {
		return _districtId;
	}

	@Override
	public void setDistrictId(long districtId) {
		_districtId = districtId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON(include = false)
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON(include = false)
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public long getCountryId() {
		return _countryId;
	}

	@Override
	public void setCountryId(long countryId) {
		_countryId = countryId;
	}

	@JSON
	@Override
	public long getCityId() {
		return _cityId;
	}

	@Override
	public void setCityId(long cityId) {
		_columnBitmask |= CITYID_COLUMN_BITMASK;

		if (!_setOriginalCityId) {
			_setOriginalCityId = true;

			_originalCityId = _cityId;
		}

		_cityId = cityId;
	}

	public long getOriginalCityId() {
		return _originalCityId;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_columnBitmask = -1L;

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public int getCountCode() {
		return _countCode;
	}

	@Override
	public void setCountCode(int countCode) {
		_countCode = countCode;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), District.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public District toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, District>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DistrictImpl districtImpl = new DistrictImpl();

		districtImpl.setDistrictId(getDistrictId());
		districtImpl.setCompanyId(getCompanyId());
		districtImpl.setGroupId(getGroupId());
		districtImpl.setUserId(getUserId());
		districtImpl.setUserName(getUserName());
		districtImpl.setCreateDate(getCreateDate());
		districtImpl.setModifiedDate(getModifiedDate());
		districtImpl.setName(getName());
		districtImpl.setCode(getCode());
		districtImpl.setCountryId(getCountryId());
		districtImpl.setCityId(getCityId());
		districtImpl.setDescription(getDescription());
		districtImpl.setPriority(getPriority());
		districtImpl.setActive(isActive());
		districtImpl.setCountCode(getCountCode());

		districtImpl.resetOriginalValues();

		return districtImpl;
	}

	@Override
	public int compareTo(District district) {
		int value = 0;

		if (getPriority() < district.getPriority()) {
			value = -1;
		}
		else if (getPriority() > district.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof District)) {
			return false;
		}

		District district = (District)obj;

		long primaryKey = district.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		DistrictModelImpl districtModelImpl = this;

		districtModelImpl._setModifiedDate = false;

		districtModelImpl._originalName = districtModelImpl._name;

		districtModelImpl._originalCode = districtModelImpl._code;

		districtModelImpl._originalCityId = districtModelImpl._cityId;

		districtModelImpl._setOriginalCityId = false;

		districtModelImpl._originalActive = districtModelImpl._active;

		districtModelImpl._setOriginalActive = false;

		districtModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<District> toCacheModel() {
		DistrictCacheModel districtCacheModel = new DistrictCacheModel();

		districtCacheModel.districtId = getDistrictId();

		districtCacheModel.companyId = getCompanyId();

		districtCacheModel.groupId = getGroupId();

		districtCacheModel.userId = getUserId();

		districtCacheModel.userName = getUserName();

		String userName = districtCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			districtCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			districtCacheModel.createDate = createDate.getTime();
		}
		else {
			districtCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			districtCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			districtCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		districtCacheModel.name = getName();

		String name = districtCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			districtCacheModel.name = null;
		}

		districtCacheModel.code = getCode();

		String code = districtCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			districtCacheModel.code = null;
		}

		districtCacheModel.countryId = getCountryId();

		districtCacheModel.cityId = getCityId();

		districtCacheModel.description = getDescription();

		String description = districtCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			districtCacheModel.description = null;
		}

		districtCacheModel.priority = getPriority();

		districtCacheModel.active = isActive();

		districtCacheModel.countCode = getCountCode();

		return districtCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<District, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<District, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<District, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((District)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<District, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<District, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<District, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((District)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, District>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _districtId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _code;
	private String _originalCode;
	private long _countryId;
	private long _cityId;
	private long _originalCityId;
	private boolean _setOriginalCityId;
	private String _description;
	private int _priority;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private int _countCode;
	private long _columnBitmask;
	private District _escapedModel;

}