/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.commoncategory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.nss.commoncategory.model.Street;
import com.nss.commoncategory.model.StreetModel;
import com.nss.commoncategory.model.StreetSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Street service. Represents a row in the &quot;nss_commoncategory_street&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>StreetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StreetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StreetImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class StreetModelImpl
	extends BaseModelImpl<Street> implements StreetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a street model instance should use the <code>Street</code> interface instead.
	 */
	public static final String TABLE_NAME = "nss_commoncategory_street";

	public static final Object[][] TABLE_COLUMNS = {
		{"streetId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"code_", Types.VARCHAR}, {"countryId", Types.BIGINT},
		{"cityId", Types.BIGINT}, {"districtId", Types.BIGINT},
		{"wardId", Types.BIGINT}, {"description", Types.VARCHAR},
		{"priority", Types.INTEGER}, {"active_", Types.BOOLEAN},
		{"countCode", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("streetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("countryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("districtId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("wardId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("countCode", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nss_commoncategory_street (streetId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(255) null,code_ VARCHAR(75) null,countryId LONG,cityId LONG,districtId LONG,wardId LONG,description STRING null,priority INTEGER,active_ BOOLEAN,countCode INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table nss_commoncategory_street";

	public static final String ORDER_BY_JPQL = " ORDER BY street.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nss_commoncategory_street.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long CITYID_COLUMN_BITMASK = 2L;

	public static final long CODE_COLUMN_BITMASK = 4L;

	public static final long DISTRICTID_COLUMN_BITMASK = 8L;

	public static final long NAME_COLUMN_BITMASK = 16L;

	public static final long WARDID_COLUMN_BITMASK = 32L;

	public static final long PRIORITY_COLUMN_BITMASK = 64L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Street toModel(StreetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Street model = new StreetImpl();

		model.setStreetId(soapModel.getStreetId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setCode(soapModel.getCode());
		model.setCountryId(soapModel.getCountryId());
		model.setCityId(soapModel.getCityId());
		model.setDistrictId(soapModel.getDistrictId());
		model.setWardId(soapModel.getWardId());
		model.setDescription(soapModel.getDescription());
		model.setPriority(soapModel.getPriority());
		model.setActive(soapModel.isActive());
		model.setCountCode(soapModel.getCountCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Street> toModels(StreetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Street> models = new ArrayList<Street>(soapModels.length);

		for (StreetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public StreetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _streetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStreetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _streetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Street.class;
	}

	@Override
	public String getModelClassName() {
		return Street.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Street, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Street, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Street, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Street)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Street, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Street, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Street)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Street, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Street, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Street>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Street.class.getClassLoader(), Street.class, ModelWrapper.class);

		try {
			Constructor<Street> constructor =
				(Constructor<Street>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Street, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Street, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Street, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Street, Object>>();
		Map<String, BiConsumer<Street, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Street, ?>>();

		attributeGetterFunctions.put("streetId", Street::getStreetId);
		attributeSetterBiConsumers.put(
			"streetId", (BiConsumer<Street, Long>)Street::setStreetId);
		attributeGetterFunctions.put("groupId", Street::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Street, Long>)Street::setGroupId);
		attributeGetterFunctions.put("companyId", Street::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Street, Long>)Street::setCompanyId);
		attributeGetterFunctions.put("userId", Street::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Street, Long>)Street::setUserId);
		attributeGetterFunctions.put("userName", Street::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Street, String>)Street::setUserName);
		attributeGetterFunctions.put("createDate", Street::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Street, Date>)Street::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Street::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Street, Date>)Street::setModifiedDate);
		attributeGetterFunctions.put("name", Street::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Street, String>)Street::setName);
		attributeGetterFunctions.put("code", Street::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<Street, String>)Street::setCode);
		attributeGetterFunctions.put("countryId", Street::getCountryId);
		attributeSetterBiConsumers.put(
			"countryId", (BiConsumer<Street, Long>)Street::setCountryId);
		attributeGetterFunctions.put("cityId", Street::getCityId);
		attributeSetterBiConsumers.put(
			"cityId", (BiConsumer<Street, Long>)Street::setCityId);
		attributeGetterFunctions.put("districtId", Street::getDistrictId);
		attributeSetterBiConsumers.put(
			"districtId", (BiConsumer<Street, Long>)Street::setDistrictId);
		attributeGetterFunctions.put("wardId", Street::getWardId);
		attributeSetterBiConsumers.put(
			"wardId", (BiConsumer<Street, Long>)Street::setWardId);
		attributeGetterFunctions.put("description", Street::getDescription);
		attributeSetterBiConsumers.put(
			"description", (BiConsumer<Street, String>)Street::setDescription);
		attributeGetterFunctions.put("priority", Street::getPriority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<Street, Integer>)Street::setPriority);
		attributeGetterFunctions.put("active", Street::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<Street, Boolean>)Street::setActive);
		attributeGetterFunctions.put("countCode", Street::getCountCode);
		attributeSetterBiConsumers.put(
			"countCode", (BiConsumer<Street, Integer>)Street::setCountCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getStreetId() {
		return _streetId;
	}

	@Override
	public void setStreetId(long streetId) {
		_streetId = streetId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON(include = false)
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON(include = false)
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public long getCountryId() {
		return _countryId;
	}

	@Override
	public void setCountryId(long countryId) {
		_countryId = countryId;
	}

	@JSON
	@Override
	public long getCityId() {
		return _cityId;
	}

	@Override
	public void setCityId(long cityId) {
		_columnBitmask |= CITYID_COLUMN_BITMASK;

		if (!_setOriginalCityId) {
			_setOriginalCityId = true;

			_originalCityId = _cityId;
		}

		_cityId = cityId;
	}

	public long getOriginalCityId() {
		return _originalCityId;
	}

	@JSON
	@Override
	public long getDistrictId() {
		return _districtId;
	}

	@Override
	public void setDistrictId(long districtId) {
		_columnBitmask |= DISTRICTID_COLUMN_BITMASK;

		if (!_setOriginalDistrictId) {
			_setOriginalDistrictId = true;

			_originalDistrictId = _districtId;
		}

		_districtId = districtId;
	}

	public long getOriginalDistrictId() {
		return _originalDistrictId;
	}

	@JSON
	@Override
	public long getWardId() {
		return _wardId;
	}

	@Override
	public void setWardId(long wardId) {
		_columnBitmask |= WARDID_COLUMN_BITMASK;

		if (!_setOriginalWardId) {
			_setOriginalWardId = true;

			_originalWardId = _wardId;
		}

		_wardId = wardId;
	}

	public long getOriginalWardId() {
		return _originalWardId;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_columnBitmask = -1L;

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public int getCountCode() {
		return _countCode;
	}

	@Override
	public void setCountCode(int countCode) {
		_countCode = countCode;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Street.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Street toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Street>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StreetImpl streetImpl = new StreetImpl();

		streetImpl.setStreetId(getStreetId());
		streetImpl.setGroupId(getGroupId());
		streetImpl.setCompanyId(getCompanyId());
		streetImpl.setUserId(getUserId());
		streetImpl.setUserName(getUserName());
		streetImpl.setCreateDate(getCreateDate());
		streetImpl.setModifiedDate(getModifiedDate());
		streetImpl.setName(getName());
		streetImpl.setCode(getCode());
		streetImpl.setCountryId(getCountryId());
		streetImpl.setCityId(getCityId());
		streetImpl.setDistrictId(getDistrictId());
		streetImpl.setWardId(getWardId());
		streetImpl.setDescription(getDescription());
		streetImpl.setPriority(getPriority());
		streetImpl.setActive(isActive());
		streetImpl.setCountCode(getCountCode());

		streetImpl.resetOriginalValues();

		return streetImpl;
	}

	@Override
	public int compareTo(Street street) {
		int value = 0;

		if (getPriority() < street.getPriority()) {
			value = -1;
		}
		else if (getPriority() > street.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Street)) {
			return false;
		}

		Street street = (Street)obj;

		long primaryKey = street.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		StreetModelImpl streetModelImpl = this;

		streetModelImpl._setModifiedDate = false;

		streetModelImpl._originalName = streetModelImpl._name;

		streetModelImpl._originalCode = streetModelImpl._code;

		streetModelImpl._originalCityId = streetModelImpl._cityId;

		streetModelImpl._setOriginalCityId = false;

		streetModelImpl._originalDistrictId = streetModelImpl._districtId;

		streetModelImpl._setOriginalDistrictId = false;

		streetModelImpl._originalWardId = streetModelImpl._wardId;

		streetModelImpl._setOriginalWardId = false;

		streetModelImpl._originalActive = streetModelImpl._active;

		streetModelImpl._setOriginalActive = false;

		streetModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Street> toCacheModel() {
		StreetCacheModel streetCacheModel = new StreetCacheModel();

		streetCacheModel.streetId = getStreetId();

		streetCacheModel.groupId = getGroupId();

		streetCacheModel.companyId = getCompanyId();

		streetCacheModel.userId = getUserId();

		streetCacheModel.userName = getUserName();

		String userName = streetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			streetCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			streetCacheModel.createDate = createDate.getTime();
		}
		else {
			streetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			streetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			streetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		streetCacheModel.name = getName();

		String name = streetCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			streetCacheModel.name = null;
		}

		streetCacheModel.code = getCode();

		String code = streetCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			streetCacheModel.code = null;
		}

		streetCacheModel.countryId = getCountryId();

		streetCacheModel.cityId = getCityId();

		streetCacheModel.districtId = getDistrictId();

		streetCacheModel.wardId = getWardId();

		streetCacheModel.description = getDescription();

		String description = streetCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			streetCacheModel.description = null;
		}

		streetCacheModel.priority = getPriority();

		streetCacheModel.active = isActive();

		streetCacheModel.countCode = getCountCode();

		return streetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Street, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Street, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Street, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Street)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Street, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Street, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Street, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Street)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Street>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _streetId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _code;
	private String _originalCode;
	private long _countryId;
	private long _cityId;
	private long _originalCityId;
	private boolean _setOriginalCityId;
	private long _districtId;
	private long _originalDistrictId;
	private boolean _setOriginalDistrictId;
	private long _wardId;
	private long _originalWardId;
	private boolean _setOriginalWardId;
	private String _description;
	private int _priority;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private int _countCode;
	private long _columnBitmask;
	private Street _escapedModel;

}