/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.commoncategory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.nss.commoncategory.model.Ward;
import com.nss.commoncategory.model.WardModel;
import com.nss.commoncategory.model.WardSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Ward service. Represents a row in the &quot;nss_platform_ward&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>WardModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WardImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class WardModelImpl extends BaseModelImpl<Ward> implements WardModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ward model instance should use the <code>Ward</code> interface instead.
	 */
	public static final String TABLE_NAME = "nss_platform_ward";

	public static final Object[][] TABLE_COLUMNS = {
		{"wardId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"code_", Types.VARCHAR}, {"countryId", Types.BIGINT},
		{"cityId", Types.BIGINT}, {"districtId", Types.BIGINT},
		{"description", Types.VARCHAR}, {"priority", Types.INTEGER},
		{"active_", Types.BOOLEAN}, {"countCode", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("wardId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("countryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("districtId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("countCode", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nss_platform_ward (wardId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(255) null,code_ VARCHAR(75) null,countryId LONG,cityId LONG,districtId LONG,description STRING null,priority INTEGER,active_ BOOLEAN,countCode INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table nss_platform_ward";

	public static final String ORDER_BY_JPQL = " ORDER BY ward.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nss_platform_ward.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long CODE_COLUMN_BITMASK = 2L;

	public static final long DISTRICTID_COLUMN_BITMASK = 4L;

	public static final long NAME_COLUMN_BITMASK = 8L;

	public static final long PRIORITY_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Ward toModel(WardSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Ward model = new WardImpl();

		model.setWardId(soapModel.getWardId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setCode(soapModel.getCode());
		model.setCountryId(soapModel.getCountryId());
		model.setCityId(soapModel.getCityId());
		model.setDistrictId(soapModel.getDistrictId());
		model.setDescription(soapModel.getDescription());
		model.setPriority(soapModel.getPriority());
		model.setActive(soapModel.isActive());
		model.setCountCode(soapModel.getCountCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Ward> toModels(WardSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Ward> models = new ArrayList<Ward>(soapModels.length);

		for (WardSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public WardModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _wardId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWardId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _wardId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Ward.class;
	}

	@Override
	public String getModelClassName() {
		return Ward.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Ward, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Ward, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ward, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Ward)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Ward, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Ward, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Ward)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Ward, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Ward, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Ward>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Ward.class.getClassLoader(), Ward.class, ModelWrapper.class);

		try {
			Constructor<Ward> constructor =
				(Constructor<Ward>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Ward, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Ward, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Ward, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Ward, Object>>();
		Map<String, BiConsumer<Ward, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Ward, ?>>();

		attributeGetterFunctions.put("wardId", Ward::getWardId);
		attributeSetterBiConsumers.put(
			"wardId", (BiConsumer<Ward, Long>)Ward::setWardId);
		attributeGetterFunctions.put("companyId", Ward::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Ward, Long>)Ward::setCompanyId);
		attributeGetterFunctions.put("groupId", Ward::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Ward, Long>)Ward::setGroupId);
		attributeGetterFunctions.put("userId", Ward::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Ward, Long>)Ward::setUserId);
		attributeGetterFunctions.put("userName", Ward::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Ward, String>)Ward::setUserName);
		attributeGetterFunctions.put("createDate", Ward::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Ward, Date>)Ward::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Ward::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Ward, Date>)Ward::setModifiedDate);
		attributeGetterFunctions.put("name", Ward::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Ward, String>)Ward::setName);
		attributeGetterFunctions.put("code", Ward::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<Ward, String>)Ward::setCode);
		attributeGetterFunctions.put("countryId", Ward::getCountryId);
		attributeSetterBiConsumers.put(
			"countryId", (BiConsumer<Ward, Long>)Ward::setCountryId);
		attributeGetterFunctions.put("cityId", Ward::getCityId);
		attributeSetterBiConsumers.put(
			"cityId", (BiConsumer<Ward, Long>)Ward::setCityId);
		attributeGetterFunctions.put("districtId", Ward::getDistrictId);
		attributeSetterBiConsumers.put(
			"districtId", (BiConsumer<Ward, Long>)Ward::setDistrictId);
		attributeGetterFunctions.put("description", Ward::getDescription);
		attributeSetterBiConsumers.put(
			"description", (BiConsumer<Ward, String>)Ward::setDescription);
		attributeGetterFunctions.put("priority", Ward::getPriority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<Ward, Integer>)Ward::setPriority);
		attributeGetterFunctions.put("active", Ward::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<Ward, Boolean>)Ward::setActive);
		attributeGetterFunctions.put("countCode", Ward::getCountCode);
		attributeSetterBiConsumers.put(
			"countCode", (BiConsumer<Ward, Integer>)Ward::setCountCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getWardId() {
		return _wardId;
	}

	@Override
	public void setWardId(long wardId) {
		_wardId = wardId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON(include = false)
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON(include = false)
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public long getCountryId() {
		return _countryId;
	}

	@Override
	public void setCountryId(long countryId) {
		_countryId = countryId;
	}

	@JSON
	@Override
	public long getCityId() {
		return _cityId;
	}

	@Override
	public void setCityId(long cityId) {
		_cityId = cityId;
	}

	@JSON
	@Override
	public long getDistrictId() {
		return _districtId;
	}

	@Override
	public void setDistrictId(long districtId) {
		_columnBitmask |= DISTRICTID_COLUMN_BITMASK;

		if (!_setOriginalDistrictId) {
			_setOriginalDistrictId = true;

			_originalDistrictId = _districtId;
		}

		_districtId = districtId;
	}

	public long getOriginalDistrictId() {
		return _originalDistrictId;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_columnBitmask = -1L;

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public int getCountCode() {
		return _countCode;
	}

	@Override
	public void setCountCode(int countCode) {
		_countCode = countCode;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Ward.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Ward toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Ward>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WardImpl wardImpl = new WardImpl();

		wardImpl.setWardId(getWardId());
		wardImpl.setCompanyId(getCompanyId());
		wardImpl.setGroupId(getGroupId());
		wardImpl.setUserId(getUserId());
		wardImpl.setUserName(getUserName());
		wardImpl.setCreateDate(getCreateDate());
		wardImpl.setModifiedDate(getModifiedDate());
		wardImpl.setName(getName());
		wardImpl.setCode(getCode());
		wardImpl.setCountryId(getCountryId());
		wardImpl.setCityId(getCityId());
		wardImpl.setDistrictId(getDistrictId());
		wardImpl.setDescription(getDescription());
		wardImpl.setPriority(getPriority());
		wardImpl.setActive(isActive());
		wardImpl.setCountCode(getCountCode());

		wardImpl.resetOriginalValues();

		return wardImpl;
	}

	@Override
	public int compareTo(Ward ward) {
		int value = 0;

		if (getPriority() < ward.getPriority()) {
			value = -1;
		}
		else if (getPriority() > ward.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Ward)) {
			return false;
		}

		Ward ward = (Ward)obj;

		long primaryKey = ward.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		WardModelImpl wardModelImpl = this;

		wardModelImpl._setModifiedDate = false;

		wardModelImpl._originalName = wardModelImpl._name;

		wardModelImpl._originalCode = wardModelImpl._code;

		wardModelImpl._originalDistrictId = wardModelImpl._districtId;

		wardModelImpl._setOriginalDistrictId = false;

		wardModelImpl._originalActive = wardModelImpl._active;

		wardModelImpl._setOriginalActive = false;

		wardModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Ward> toCacheModel() {
		WardCacheModel wardCacheModel = new WardCacheModel();

		wardCacheModel.wardId = getWardId();

		wardCacheModel.companyId = getCompanyId();

		wardCacheModel.groupId = getGroupId();

		wardCacheModel.userId = getUserId();

		wardCacheModel.userName = getUserName();

		String userName = wardCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			wardCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			wardCacheModel.createDate = createDate.getTime();
		}
		else {
			wardCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			wardCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			wardCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		wardCacheModel.name = getName();

		String name = wardCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			wardCacheModel.name = null;
		}

		wardCacheModel.code = getCode();

		String code = wardCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			wardCacheModel.code = null;
		}

		wardCacheModel.countryId = getCountryId();

		wardCacheModel.cityId = getCityId();

		wardCacheModel.districtId = getDistrictId();

		wardCacheModel.description = getDescription();

		String description = wardCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			wardCacheModel.description = null;
		}

		wardCacheModel.priority = getPriority();

		wardCacheModel.active = isActive();

		wardCacheModel.countCode = getCountCode();

		return wardCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Ward, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Ward, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ward, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Ward)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Ward, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Ward, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ward, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Ward)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Ward>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _wardId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _code;
	private String _originalCode;
	private long _countryId;
	private long _cityId;
	private long _districtId;
	private long _originalDistrictId;
	private boolean _setOriginalDistrictId;
	private String _description;
	private int _priority;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private int _countCode;
	private long _columnBitmask;
	private Ward _escapedModel;

}