/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.taskcategory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TaskType service. Represents a row in the &quot;nss_taskcategory_tasktype&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nss.taskcategory.model.impl.TaskTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nss.taskcategory.model.impl.TaskTypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskType
 * @generated
 */
@ProviderType
public interface TaskTypeModel
	extends BaseModel<TaskType>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task type model instance should use the {@link TaskType} interface instead.
	 */

	/**
	 * Returns the primary key of this task type.
	 *
	 * @return the primary key of this task type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task type.
	 *
	 * @param primaryKey the primary key of this task type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task type ID of this task type.
	 *
	 * @return the task type ID of this task type
	 */
	public long getTaskTypeId();

	/**
	 * Sets the task type ID of this task type.
	 *
	 * @param taskTypeId the task type ID of this task type
	 */
	public void setTaskTypeId(long taskTypeId);

	/**
	 * Returns the group ID of this task type.
	 *
	 * @return the group ID of this task type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this task type.
	 *
	 * @param groupId the group ID of this task type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this task type.
	 *
	 * @return the company ID of this task type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this task type.
	 *
	 * @param companyId the company ID of this task type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this task type.
	 *
	 * @return the user ID of this task type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this task type.
	 *
	 * @param userId the user ID of this task type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this task type.
	 *
	 * @return the user uuid of this task type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this task type.
	 *
	 * @param userUuid the user uuid of this task type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this task type.
	 *
	 * @return the user name of this task type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this task type.
	 *
	 * @param userName the user name of this task type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this task type.
	 *
	 * @return the create date of this task type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this task type.
	 *
	 * @param createDate the create date of this task type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this task type.
	 *
	 * @return the modified date of this task type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task type.
	 *
	 * @param modifiedDate the modified date of this task type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this task type.
	 *
	 * @return the name of this task type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this task type.
	 *
	 * @param name the name of this task type
	 */
	public void setName(String name);

	/**
	 * Returns the code of this task type.
	 *
	 * @return the code of this task type
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this task type.
	 *
	 * @param code the code of this task type
	 */
	public void setCode(String code);

	/**
	 * Returns the priority of this task type.
	 *
	 * @return the priority of this task type
	 */
	public int getPriority();

	/**
	 * Sets the priority of this task type.
	 *
	 * @param priority the priority of this task type
	 */
	public void setPriority(int priority);

	/**
	 * Returns the active of this task type.
	 *
	 * @return the active of this task type
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this task type is active.
	 *
	 * @return <code>true</code> if this task type is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this task type is active.
	 *
	 * @param active the active of this task type
	 */
	public void setActive(boolean active);

	/**
	 * Returns the description of this task type.
	 *
	 * @return the description of this task type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this task type.
	 *
	 * @param description the description of this task type
	 */
	public void setDescription(String description);

}