/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.taskcategory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.nss.taskcategory.model.Investor;
import com.nss.taskcategory.model.InvestorModel;
import com.nss.taskcategory.model.InvestorSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Investor service. Represents a row in the &quot;nss_taskcategory_investor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>InvestorModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InvestorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InvestorImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class InvestorModelImpl
	extends BaseModelImpl<Investor> implements InvestorModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a investor model instance should use the <code>Investor</code> interface instead.
	 */
	public static final String TABLE_NAME = "nss_taskcategory_investor";

	public static final Object[][] TABLE_COLUMNS = {
		{"investorId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"phoneNumber", Types.VARCHAR}, {"email", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("investorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phoneNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nss_taskcategory_investor (investorId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,phoneNumber VARCHAR(75) null,email VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nss_taskcategory_investor";

	public static final String ORDER_BY_JPQL =
		" ORDER BY investor.investorId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nss_taskcategory_investor.investorId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long INVESTORID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Investor toModel(InvestorSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Investor model = new InvestorImpl();

		model.setInvestorId(soapModel.getInvestorId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setPhoneNumber(soapModel.getPhoneNumber());
		model.setEmail(soapModel.getEmail());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Investor> toModels(InvestorSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Investor> models = new ArrayList<Investor>(soapModels.length);

		for (InvestorSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public InvestorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _investorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInvestorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _investorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Investor.class;
	}

	@Override
	public String getModelClassName() {
		return Investor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Investor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Investor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Investor, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Investor)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Investor, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Investor, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Investor)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Investor, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Investor, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Investor>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Investor.class.getClassLoader(), Investor.class,
			ModelWrapper.class);

		try {
			Constructor<Investor> constructor =
				(Constructor<Investor>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Investor, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Investor, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Investor, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Investor, Object>>();
		Map<String, BiConsumer<Investor, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Investor, ?>>();

		attributeGetterFunctions.put("investorId", Investor::getInvestorId);
		attributeSetterBiConsumers.put(
			"investorId", (BiConsumer<Investor, Long>)Investor::setInvestorId);
		attributeGetterFunctions.put("groupId", Investor::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Investor, Long>)Investor::setGroupId);
		attributeGetterFunctions.put("companyId", Investor::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Investor, Long>)Investor::setCompanyId);
		attributeGetterFunctions.put("userId", Investor::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Investor, Long>)Investor::setUserId);
		attributeGetterFunctions.put("userName", Investor::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Investor, String>)Investor::setUserName);
		attributeGetterFunctions.put("createDate", Investor::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Investor, Date>)Investor::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Investor::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Investor, Date>)Investor::setModifiedDate);
		attributeGetterFunctions.put("name", Investor::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Investor, String>)Investor::setName);
		attributeGetterFunctions.put("phoneNumber", Investor::getPhoneNumber);
		attributeSetterBiConsumers.put(
			"phoneNumber",
			(BiConsumer<Investor, String>)Investor::setPhoneNumber);
		attributeGetterFunctions.put("email", Investor::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<Investor, String>)Investor::setEmail);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getInvestorId() {
		return _investorId;
	}

	@Override
	public void setInvestorId(long investorId) {
		_columnBitmask = -1L;

		_investorId = investorId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getPhoneNumber() {
		if (_phoneNumber == null) {
			return "";
		}
		else {
			return _phoneNumber;
		}
	}

	@Override
	public void setPhoneNumber(String phoneNumber) {
		_phoneNumber = phoneNumber;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Investor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Investor toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Investor>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InvestorImpl investorImpl = new InvestorImpl();

		investorImpl.setInvestorId(getInvestorId());
		investorImpl.setGroupId(getGroupId());
		investorImpl.setCompanyId(getCompanyId());
		investorImpl.setUserId(getUserId());
		investorImpl.setUserName(getUserName());
		investorImpl.setCreateDate(getCreateDate());
		investorImpl.setModifiedDate(getModifiedDate());
		investorImpl.setName(getName());
		investorImpl.setPhoneNumber(getPhoneNumber());
		investorImpl.setEmail(getEmail());

		investorImpl.resetOriginalValues();

		return investorImpl;
	}

	@Override
	public int compareTo(Investor investor) {
		int value = 0;

		if (getInvestorId() < investor.getInvestorId()) {
			value = -1;
		}
		else if (getInvestorId() > investor.getInvestorId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Investor)) {
			return false;
		}

		Investor investor = (Investor)obj;

		long primaryKey = investor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		InvestorModelImpl investorModelImpl = this;

		investorModelImpl._originalCompanyId = investorModelImpl._companyId;

		investorModelImpl._setOriginalCompanyId = false;

		investorModelImpl._setModifiedDate = false;

		investorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Investor> toCacheModel() {
		InvestorCacheModel investorCacheModel = new InvestorCacheModel();

		investorCacheModel.investorId = getInvestorId();

		investorCacheModel.groupId = getGroupId();

		investorCacheModel.companyId = getCompanyId();

		investorCacheModel.userId = getUserId();

		investorCacheModel.userName = getUserName();

		String userName = investorCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			investorCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			investorCacheModel.createDate = createDate.getTime();
		}
		else {
			investorCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			investorCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			investorCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		investorCacheModel.name = getName();

		String name = investorCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			investorCacheModel.name = null;
		}

		investorCacheModel.phoneNumber = getPhoneNumber();

		String phoneNumber = investorCacheModel.phoneNumber;

		if ((phoneNumber != null) && (phoneNumber.length() == 0)) {
			investorCacheModel.phoneNumber = null;
		}

		investorCacheModel.email = getEmail();

		String email = investorCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			investorCacheModel.email = null;
		}

		return investorCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Investor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Investor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Investor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Investor)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Investor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Investor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Investor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Investor)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Investor>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _investorId;
	private long _groupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _phoneNumber;
	private String _email;
	private long _columnBitmask;
	private Investor _escapedModel;

}