/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.taskcategory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.nss.taskcategory.model.TaskStatus;
import com.nss.taskcategory.model.TaskStatusModel;
import com.nss.taskcategory.model.TaskStatusSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the TaskStatus service. Represents a row in the &quot;nss_taskcategory_taskstatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TaskStatusModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskStatusImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TaskStatusModelImpl
	extends BaseModelImpl<TaskStatus> implements TaskStatusModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a task status model instance should use the <code>TaskStatus</code> interface instead.
	 */
	public static final String TABLE_NAME = "nss_taskcategory_taskstatus";

	public static final Object[][] TABLE_COLUMNS = {
		{"taskStatusId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"code_", Types.VARCHAR}, {"priority", Types.INTEGER},
		{"active_", Types.BOOLEAN}, {"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("taskStatusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nss_taskcategory_taskstatus (taskStatusId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(255) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(255) null,code_ VARCHAR(75) null,priority INTEGER,active_ BOOLEAN,description STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table nss_taskcategory_taskstatus";

	public static final String ORDER_BY_JPQL =
		" ORDER BY taskStatus.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nss_taskcategory_taskstatus.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long CODE_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long PRIORITY_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TaskStatus toModel(TaskStatusSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TaskStatus model = new TaskStatusImpl();

		model.setTaskStatusId(soapModel.getTaskStatusId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setCode(soapModel.getCode());
		model.setPriority(soapModel.getPriority());
		model.setActive(soapModel.isActive());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TaskStatus> toModels(TaskStatusSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TaskStatus> models = new ArrayList<TaskStatus>(soapModels.length);

		for (TaskStatusSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TaskStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taskStatusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaskStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taskStatusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaskStatus.class;
	}

	@Override
	public String getModelClassName() {
		return TaskStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TaskStatus, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TaskStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskStatus, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TaskStatus)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TaskStatus, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TaskStatus, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TaskStatus)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TaskStatus, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TaskStatus, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TaskStatus>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TaskStatus.class.getClassLoader(), TaskStatus.class,
			ModelWrapper.class);

		try {
			Constructor<TaskStatus> constructor =
				(Constructor<TaskStatus>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<TaskStatus, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TaskStatus, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TaskStatus, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TaskStatus, Object>>();
		Map<String, BiConsumer<TaskStatus, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TaskStatus, ?>>();

		attributeGetterFunctions.put(
			"taskStatusId", TaskStatus::getTaskStatusId);
		attributeSetterBiConsumers.put(
			"taskStatusId",
			(BiConsumer<TaskStatus, Long>)TaskStatus::setTaskStatusId);
		attributeGetterFunctions.put("groupId", TaskStatus::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<TaskStatus, Long>)TaskStatus::setGroupId);
		attributeGetterFunctions.put("companyId", TaskStatus::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TaskStatus, Long>)TaskStatus::setCompanyId);
		attributeGetterFunctions.put("userId", TaskStatus::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<TaskStatus, Long>)TaskStatus::setUserId);
		attributeGetterFunctions.put("userName", TaskStatus::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TaskStatus, String>)TaskStatus::setUserName);
		attributeGetterFunctions.put("createDate", TaskStatus::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TaskStatus, Date>)TaskStatus::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TaskStatus::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TaskStatus, Date>)TaskStatus::setModifiedDate);
		attributeGetterFunctions.put("name", TaskStatus::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<TaskStatus, String>)TaskStatus::setName);
		attributeGetterFunctions.put("code", TaskStatus::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<TaskStatus, String>)TaskStatus::setCode);
		attributeGetterFunctions.put("priority", TaskStatus::getPriority);
		attributeSetterBiConsumers.put(
			"priority",
			(BiConsumer<TaskStatus, Integer>)TaskStatus::setPriority);
		attributeGetterFunctions.put("active", TaskStatus::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<TaskStatus, Boolean>)TaskStatus::setActive);
		attributeGetterFunctions.put("description", TaskStatus::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<TaskStatus, String>)TaskStatus::setDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTaskStatusId() {
		return _taskStatusId;
	}

	@Override
	public void setTaskStatusId(long taskStatusId) {
		_taskStatusId = taskStatusId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_columnBitmask = -1L;

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TaskStatus.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaskStatus toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TaskStatus>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaskStatusImpl taskStatusImpl = new TaskStatusImpl();

		taskStatusImpl.setTaskStatusId(getTaskStatusId());
		taskStatusImpl.setGroupId(getGroupId());
		taskStatusImpl.setCompanyId(getCompanyId());
		taskStatusImpl.setUserId(getUserId());
		taskStatusImpl.setUserName(getUserName());
		taskStatusImpl.setCreateDate(getCreateDate());
		taskStatusImpl.setModifiedDate(getModifiedDate());
		taskStatusImpl.setName(getName());
		taskStatusImpl.setCode(getCode());
		taskStatusImpl.setPriority(getPriority());
		taskStatusImpl.setActive(isActive());
		taskStatusImpl.setDescription(getDescription());

		taskStatusImpl.resetOriginalValues();

		return taskStatusImpl;
	}

	@Override
	public int compareTo(TaskStatus taskStatus) {
		int value = 0;

		if (getPriority() < taskStatus.getPriority()) {
			value = -1;
		}
		else if (getPriority() > taskStatus.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TaskStatus)) {
			return false;
		}

		TaskStatus taskStatus = (TaskStatus)obj;

		long primaryKey = taskStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TaskStatusModelImpl taskStatusModelImpl = this;

		taskStatusModelImpl._originalCompanyId = taskStatusModelImpl._companyId;

		taskStatusModelImpl._setOriginalCompanyId = false;

		taskStatusModelImpl._setModifiedDate = false;

		taskStatusModelImpl._originalCode = taskStatusModelImpl._code;

		taskStatusModelImpl._originalActive = taskStatusModelImpl._active;

		taskStatusModelImpl._setOriginalActive = false;

		taskStatusModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaskStatus> toCacheModel() {
		TaskStatusCacheModel taskStatusCacheModel = new TaskStatusCacheModel();

		taskStatusCacheModel.taskStatusId = getTaskStatusId();

		taskStatusCacheModel.groupId = getGroupId();

		taskStatusCacheModel.companyId = getCompanyId();

		taskStatusCacheModel.userId = getUserId();

		taskStatusCacheModel.userName = getUserName();

		String userName = taskStatusCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			taskStatusCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			taskStatusCacheModel.createDate = createDate.getTime();
		}
		else {
			taskStatusCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			taskStatusCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			taskStatusCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		taskStatusCacheModel.name = getName();

		String name = taskStatusCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			taskStatusCacheModel.name = null;
		}

		taskStatusCacheModel.code = getCode();

		String code = taskStatusCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			taskStatusCacheModel.code = null;
		}

		taskStatusCacheModel.priority = getPriority();

		taskStatusCacheModel.active = isActive();

		taskStatusCacheModel.description = getDescription();

		String description = taskStatusCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			taskStatusCacheModel.description = null;
		}

		return taskStatusCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TaskStatus, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TaskStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TaskStatus)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TaskStatus, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TaskStatus, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TaskStatus)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TaskStatus>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _taskStatusId;
	private long _groupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _code;
	private String _originalCode;
	private int _priority;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private String _description;
	private long _columnBitmask;
	private TaskStatus _escapedModel;

}