/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.taskcategory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.nss.taskcategory.model.TaskType;
import com.nss.taskcategory.model.TaskTypeModel;
import com.nss.taskcategory.model.TaskTypeSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the TaskType service. Represents a row in the &quot;nss_taskcategory_tasktype&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TaskTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskTypeImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TaskTypeModelImpl
	extends BaseModelImpl<TaskType> implements TaskTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a task type model instance should use the <code>TaskType</code> interface instead.
	 */
	public static final String TABLE_NAME = "nss_taskcategory_tasktype";

	public static final Object[][] TABLE_COLUMNS = {
		{"taskTypeId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"code_", Types.VARCHAR}, {"priority", Types.INTEGER},
		{"active_", Types.BOOLEAN}, {"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("taskTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table nss_taskcategory_tasktype (taskTypeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,code_ VARCHAR(75) null,priority INTEGER,active_ BOOLEAN,description VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table nss_taskcategory_tasktype";

	public static final String ORDER_BY_JPQL =
		" ORDER BY taskType.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY nss_taskcategory_tasktype.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long CODE_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long PRIORITY_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TaskType toModel(TaskTypeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TaskType model = new TaskTypeImpl();

		model.setTaskTypeId(soapModel.getTaskTypeId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setCode(soapModel.getCode());
		model.setPriority(soapModel.getPriority());
		model.setActive(soapModel.isActive());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TaskType> toModels(TaskTypeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TaskType> models = new ArrayList<TaskType>(soapModels.length);

		for (TaskTypeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TaskTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taskTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaskTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taskTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaskType.class;
	}

	@Override
	public String getModelClassName() {
		return TaskType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TaskType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TaskType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TaskType)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TaskType, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TaskType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TaskType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TaskType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TaskType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TaskType>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TaskType.class.getClassLoader(), TaskType.class,
			ModelWrapper.class);

		try {
			Constructor<TaskType> constructor =
				(Constructor<TaskType>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<TaskType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TaskType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TaskType, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TaskType, Object>>();
		Map<String, BiConsumer<TaskType, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TaskType, ?>>();

		attributeGetterFunctions.put("taskTypeId", TaskType::getTaskTypeId);
		attributeSetterBiConsumers.put(
			"taskTypeId", (BiConsumer<TaskType, Long>)TaskType::setTaskTypeId);
		attributeGetterFunctions.put("groupId", TaskType::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<TaskType, Long>)TaskType::setGroupId);
		attributeGetterFunctions.put("companyId", TaskType::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<TaskType, Long>)TaskType::setCompanyId);
		attributeGetterFunctions.put("userId", TaskType::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<TaskType, Long>)TaskType::setUserId);
		attributeGetterFunctions.put("userName", TaskType::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<TaskType, String>)TaskType::setUserName);
		attributeGetterFunctions.put("createDate", TaskType::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<TaskType, Date>)TaskType::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", TaskType::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TaskType, Date>)TaskType::setModifiedDate);
		attributeGetterFunctions.put("name", TaskType::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<TaskType, String>)TaskType::setName);
		attributeGetterFunctions.put("code", TaskType::getCode);
		attributeSetterBiConsumers.put(
			"code", (BiConsumer<TaskType, String>)TaskType::setCode);
		attributeGetterFunctions.put("priority", TaskType::getPriority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<TaskType, Integer>)TaskType::setPriority);
		attributeGetterFunctions.put("active", TaskType::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<TaskType, Boolean>)TaskType::setActive);
		attributeGetterFunctions.put("description", TaskType::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<TaskType, String>)TaskType::setDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTaskTypeId() {
		return _taskTypeId;
	}

	@Override
	public void setTaskTypeId(long taskTypeId) {
		_taskTypeId = taskTypeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask |= CODE_COLUMN_BITMASK;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_columnBitmask = -1L;

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TaskType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaskType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TaskType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaskTypeImpl taskTypeImpl = new TaskTypeImpl();

		taskTypeImpl.setTaskTypeId(getTaskTypeId());
		taskTypeImpl.setGroupId(getGroupId());
		taskTypeImpl.setCompanyId(getCompanyId());
		taskTypeImpl.setUserId(getUserId());
		taskTypeImpl.setUserName(getUserName());
		taskTypeImpl.setCreateDate(getCreateDate());
		taskTypeImpl.setModifiedDate(getModifiedDate());
		taskTypeImpl.setName(getName());
		taskTypeImpl.setCode(getCode());
		taskTypeImpl.setPriority(getPriority());
		taskTypeImpl.setActive(isActive());
		taskTypeImpl.setDescription(getDescription());

		taskTypeImpl.resetOriginalValues();

		return taskTypeImpl;
	}

	@Override
	public int compareTo(TaskType taskType) {
		int value = 0;

		if (getPriority() < taskType.getPriority()) {
			value = -1;
		}
		else if (getPriority() > taskType.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TaskType)) {
			return false;
		}

		TaskType taskType = (TaskType)obj;

		long primaryKey = taskType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TaskTypeModelImpl taskTypeModelImpl = this;

		taskTypeModelImpl._originalCompanyId = taskTypeModelImpl._companyId;

		taskTypeModelImpl._setOriginalCompanyId = false;

		taskTypeModelImpl._setModifiedDate = false;

		taskTypeModelImpl._originalCode = taskTypeModelImpl._code;

		taskTypeModelImpl._originalActive = taskTypeModelImpl._active;

		taskTypeModelImpl._setOriginalActive = false;

		taskTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaskType> toCacheModel() {
		TaskTypeCacheModel taskTypeCacheModel = new TaskTypeCacheModel();

		taskTypeCacheModel.taskTypeId = getTaskTypeId();

		taskTypeCacheModel.groupId = getGroupId();

		taskTypeCacheModel.companyId = getCompanyId();

		taskTypeCacheModel.userId = getUserId();

		taskTypeCacheModel.userName = getUserName();

		String userName = taskTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			taskTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			taskTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			taskTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			taskTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			taskTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		taskTypeCacheModel.name = getName();

		String name = taskTypeCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			taskTypeCacheModel.name = null;
		}

		taskTypeCacheModel.code = getCode();

		String code = taskTypeCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			taskTypeCacheModel.code = null;
		}

		taskTypeCacheModel.priority = getPriority();

		taskTypeCacheModel.active = isActive();

		taskTypeCacheModel.description = getDescription();

		String description = taskTypeCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			taskTypeCacheModel.description = null;
		}

		return taskTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TaskType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TaskType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TaskType)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TaskType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TaskType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TaskType)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TaskType>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _taskTypeId;
	private long _groupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _code;
	private String _originalCode;
	private int _priority;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private String _description;
	private long _columnBitmask;
	private TaskType _escapedModel;

}