/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.commoncategory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Address service. Represents a row in the &quot;nss_commoncategory_address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nss.commoncategory.model.impl.AddressModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nss.commoncategory.model.impl.AddressImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Address
 * @generated
 */
@ProviderType
public interface AddressModel
	extends AttachedModel, BaseModel<Address>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a address model instance should use the {@link Address} interface instead.
	 */

	/**
	 * Returns the primary key of this address.
	 *
	 * @return the primary key of this address
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this address.
	 *
	 * @param primaryKey the primary key of this address
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the address ID of this address.
	 *
	 * @return the address ID of this address
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this address.
	 *
	 * @param addressId the address ID of this address
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the group ID of this address.
	 *
	 * @return the group ID of this address
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this address.
	 *
	 * @param groupId the group ID of this address
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this address.
	 *
	 * @return the company ID of this address
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this address.
	 *
	 * @param companyId the company ID of this address
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this address.
	 *
	 * @return the user ID of this address
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this address.
	 *
	 * @param userId the user ID of this address
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this address.
	 *
	 * @return the user uuid of this address
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this address.
	 *
	 * @param userUuid the user uuid of this address
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this address.
	 *
	 * @return the user name of this address
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this address.
	 *
	 * @param userName the user name of this address
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this address.
	 *
	 * @return the create date of this address
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this address.
	 *
	 * @param createDate the create date of this address
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this address.
	 *
	 * @return the modified date of this address
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this address.
	 *
	 * @param modifiedDate the modified date of this address
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this address.
	 *
	 * @return the fully qualified class name of this address
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this address.
	 *
	 * @return the class name ID of this address
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this address.
	 *
	 * @param classNameId the class name ID of this address
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this address.
	 *
	 * @return the class pk of this address
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this address.
	 *
	 * @param classPK the class pk of this address
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the country ID of this address.
	 *
	 * @return the country ID of this address
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this address.
	 *
	 * @param countryId the country ID of this address
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the city ID of this address.
	 *
	 * @return the city ID of this address
	 */
	public long getCityId();

	/**
	 * Sets the city ID of this address.
	 *
	 * @param cityId the city ID of this address
	 */
	public void setCityId(long cityId);

	/**
	 * Returns the district ID of this address.
	 *
	 * @return the district ID of this address
	 */
	public long getDistrictId();

	/**
	 * Sets the district ID of this address.
	 *
	 * @param districtId the district ID of this address
	 */
	public void setDistrictId(long districtId);

	/**
	 * Returns the ward ID of this address.
	 *
	 * @return the ward ID of this address
	 */
	public long getWardId();

	/**
	 * Sets the ward ID of this address.
	 *
	 * @param wardId the ward ID of this address
	 */
	public void setWardId(long wardId);

	/**
	 * Returns the street ID of this address.
	 *
	 * @return the street ID of this address
	 */
	public long getStreetId();

	/**
	 * Sets the street ID of this address.
	 *
	 * @param streetId the street ID of this address
	 */
	public void setStreetId(long streetId);

	/**
	 * Returns the street other of this address.
	 *
	 * @return the street other of this address
	 */
	@AutoEscape
	public String getStreetOther();

	/**
	 * Sets the street other of this address.
	 *
	 * @param streetOther the street other of this address
	 */
	public void setStreetOther(String streetOther);

	/**
	 * Returns the quarter of this address.
	 *
	 * @return the quarter of this address
	 */
	@AutoEscape
	public String getQuarter();

	/**
	 * Sets the quarter of this address.
	 *
	 * @param quarter the quarter of this address
	 */
	public void setQuarter(String quarter);

	/**
	 * Returns the house number of this address.
	 *
	 * @return the house number of this address
	 */
	@AutoEscape
	public String getHouseNumber();

	/**
	 * Sets the house number of this address.
	 *
	 * @param houseNumber the house number of this address
	 */
	public void setHouseNumber(String houseNumber);

	/**
	 * Returns the building of this address.
	 *
	 * @return the building of this address
	 */
	@AutoEscape
	public String getBuilding();

	/**
	 * Sets the building of this address.
	 *
	 * @param building the building of this address
	 */
	public void setBuilding(String building);

	/**
	 * Returns the floor of this address.
	 *
	 * @return the floor of this address
	 */
	@AutoEscape
	public String getFloor();

	/**
	 * Sets the floor of this address.
	 *
	 * @param floor the floor of this address
	 */
	public void setFloor(String floor);

	/**
	 * Returns the room of this address.
	 *
	 * @return the room of this address
	 */
	@AutoEscape
	public String getRoom();

	/**
	 * Sets the room of this address.
	 *
	 * @param room the room of this address
	 */
	public void setRoom(String room);

	/**
	 * Returns the type of this address.
	 *
	 * @return the type of this address
	 */
	public int getType();

	/**
	 * Sets the type of this address.
	 *
	 * @param type the type of this address
	 */
	public void setType(int type);

}