/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.commoncategory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the City service. Represents a row in the &quot;nss_platform_city&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nss.commoncategory.model.impl.CityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nss.commoncategory.model.impl.CityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see City
 * @generated
 */
@ProviderType
public interface CityModel extends BaseModel<City>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a city model instance should use the {@link City} interface instead.
	 */

	/**
	 * Returns the primary key of this city.
	 *
	 * @return the primary key of this city
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this city.
	 *
	 * @param primaryKey the primary key of this city
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the city ID of this city.
	 *
	 * @return the city ID of this city
	 */
	public long getCityId();

	/**
	 * Sets the city ID of this city.
	 *
	 * @param cityId the city ID of this city
	 */
	public void setCityId(long cityId);

	/**
	 * Returns the company ID of this city.
	 *
	 * @return the company ID of this city
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this city.
	 *
	 * @param companyId the company ID of this city
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this city.
	 *
	 * @return the group ID of this city
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this city.
	 *
	 * @param groupId the group ID of this city
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this city.
	 *
	 * @return the user ID of this city
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this city.
	 *
	 * @param userId the user ID of this city
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this city.
	 *
	 * @return the user uuid of this city
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this city.
	 *
	 * @param userUuid the user uuid of this city
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this city.
	 *
	 * @return the user name of this city
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this city.
	 *
	 * @param userName the user name of this city
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this city.
	 *
	 * @return the create date of this city
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this city.
	 *
	 * @param createDate the create date of this city
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this city.
	 *
	 * @return the modified date of this city
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this city.
	 *
	 * @param modifiedDate the modified date of this city
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this city.
	 *
	 * @return the name of this city
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this city.
	 *
	 * @param name the name of this city
	 */
	public void setName(String name);

	/**
	 * Returns the code of this city.
	 *
	 * @return the code of this city
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this city.
	 *
	 * @param code the code of this city
	 */
	public void setCode(String code);

	/**
	 * Returns the country ID of this city.
	 *
	 * @return the country ID of this city
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this city.
	 *
	 * @param countryId the country ID of this city
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the description of this city.
	 *
	 * @return the description of this city
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this city.
	 *
	 * @param description the description of this city
	 */
	public void setDescription(String description);

	/**
	 * Returns the priority of this city.
	 *
	 * @return the priority of this city
	 */
	public int getPriority();

	/**
	 * Sets the priority of this city.
	 *
	 * @param priority the priority of this city
	 */
	public void setPriority(int priority);

	/**
	 * Returns the active of this city.
	 *
	 * @return the active of this city
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this city is active.
	 *
	 * @return <code>true</code> if this city is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this city is active.
	 *
	 * @param active the active of this city
	 */
	public void setActive(boolean active);

	/**
	 * Returns the count code of this city.
	 *
	 * @return the count code of this city
	 */
	public int getCountCode();

	/**
	 * Sets the count code of this city.
	 *
	 * @param countCode the count code of this city
	 */
	public void setCountCode(int countCode);

}