/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nss.commoncategory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Continent service. Represents a row in the &quot;nss_commoncategory_continent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nss.commoncategory.model.impl.ContinentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nss.commoncategory.model.impl.ContinentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Continent
 * @generated
 */
@ProviderType
public interface ContinentModel
	extends BaseModel<Continent>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a continent model instance should use the {@link Continent} interface instead.
	 */

	/**
	 * Returns the primary key of this continent.
	 *
	 * @return the primary key of this continent
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this continent.
	 *
	 * @param primaryKey the primary key of this continent
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the continent ID of this continent.
	 *
	 * @return the continent ID of this continent
	 */
	public long getContinentId();

	/**
	 * Sets the continent ID of this continent.
	 *
	 * @param continentId the continent ID of this continent
	 */
	public void setContinentId(long continentId);

	/**
	 * Returns the company ID of this continent.
	 *
	 * @return the company ID of this continent
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this continent.
	 *
	 * @param companyId the company ID of this continent
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this continent.
	 *
	 * @return the group ID of this continent
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this continent.
	 *
	 * @param groupId the group ID of this continent
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this continent.
	 *
	 * @return the user ID of this continent
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this continent.
	 *
	 * @param userId the user ID of this continent
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this continent.
	 *
	 * @return the user uuid of this continent
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this continent.
	 *
	 * @param userUuid the user uuid of this continent
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this continent.
	 *
	 * @return the user name of this continent
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this continent.
	 *
	 * @param userName the user name of this continent
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this continent.
	 *
	 * @return the create date of this continent
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this continent.
	 *
	 * @param createDate the create date of this continent
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this continent.
	 *
	 * @return the modified date of this continent
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this continent.
	 *
	 * @param modifiedDate the modified date of this continent
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this continent.
	 *
	 * @return the name of this continent
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this continent.
	 *
	 * @param name the name of this continent
	 */
	public void setName(String name);

	/**
	 * Returns the international name of this continent.
	 *
	 * @return the international name of this continent
	 */
	@AutoEscape
	public String getInternationalName();

	/**
	 * Sets the international name of this continent.
	 *
	 * @param internationalName the international name of this continent
	 */
	public void setInternationalName(String internationalName);

	/**
	 * Returns the code of this continent.
	 *
	 * @return the code of this continent
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this continent.
	 *
	 * @param code the code of this continent
	 */
	public void setCode(String code);

	/**
	 * Returns the description of this continent.
	 *
	 * @return the description of this continent
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this continent.
	 *
	 * @param description the description of this continent
	 */
	public void setDescription(String description);

	/**
	 * Returns the priority of this continent.
	 *
	 * @return the priority of this continent
	 */
	public int getPriority();

	/**
	 * Sets the priority of this continent.
	 *
	 * @param priority the priority of this continent
	 */
	public void setPriority(int priority);

	/**
	 * Returns the active of this continent.
	 *
	 * @return the active of this continent
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this continent is active.
	 *
	 * @return <code>true</code> if this continent is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this continent is active.
	 *
	 * @param active the active of this continent
	 */
	public void setActive(boolean active);

	/**
	 * Returns the count code of this continent.
	 *
	 * @return the count code of this continent
	 */
	public int getCountCode();

	/**
	 * Sets the count code of this continent.
	 *
	 * @param countCode the count code of this continent
	 */
	public void setCountCode(int countCode);

}